name: 'RSS to JSON'
description: 'A GitHub Action which crawls RSS feeds and outputs a JSON file.'
branding:
  icon: rss
  color: orange
inputs:
  source:
    description: The source directory and filename (incl. .yaml)
    required: false
    default: feeds.yaml
  target:
    description: The target directory and filename (incl. .json)
    required: false
    default: feeds.json
  sortBy:
    description: Sort the feed items by a field. Default is isoDate.
    required: false
    default: isoDate
  sortOrder:
    description: Specify the order direction. 'desc' or 'asc'. Default is desc.
    required: false
    default: desc
runs:
  using: 'node12'
  main: 'index.js'
